/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package redsocial;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import redsocial.GrafoLA;

/**
 *
 * @author Antonio Guzzo
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    GrafoLA grafo;

    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cargarArchivo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        mostrarGrafo = new javax.swing.JButton();
        identificar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        actualizar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        usuario2 = new javax.swing.JTextField();
        inputAgregar = new javax.swing.JTextField();
        agregar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        inputEliminar = new javax.swing.JTextField();
        usuario1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        enlazar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Análisis de redes sociales");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        cargarArchivo.setText("Cargar archivo");
        cargarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarArchivoActionPerformed(evt);
            }
        });
        jPanel1.add(cargarArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel2.setText("Agregar archivo informacion inicial");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        mostrarGrafo.setText("Mostrar grafo");
        jPanel1.add(mostrarGrafo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, -1, -1));

        identificar.setText("Identificar");
        identificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                identificarActionPerformed(evt);
            }
        });
        jPanel1.add(identificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel3.setText("Componentes fuertemente conectados");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        actualizar.setText("Actualizar repositorio");
        jPanel1.add(actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, -1, -1));

        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        jPanel1.add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, -1));

        jLabel4.setText("Eliminar usuario");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));
        jPanel1.add(usuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 110, -1));
        jPanel1.add(inputAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 100, -1));

        agregar.setText("agregar");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });
        jPanel1.add(agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, -1, -1));

        jLabel5.setText("Agregar usuario");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, -1, -1));
        jPanel1.add(inputEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 100, -1));
        jPanel1.add(usuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 110, -1));

        jLabel6.setText("Agregar relacion");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, -1, -1));

        enlazar.setText("Enlazar");
        enlazar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enlazarActionPerformed(evt);
            }
        });
        jPanel1.add(enlazar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void identificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_identificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_identificarActionPerformed

    private void cargarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarArchivoActionPerformed
        // Se crea el Objeto JFileChooser
        JFileChooser fc = new JFileChooser();

        // Se crea el filtro para que solo se acepte TXT
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("*.TXT", "txt");

        // Se le indica el filtro
        fc.setFileFilter(filtro);

        // Se abre la ventana, y se guarda la op seleccionada por el usuario
        int seleccion = fc.showOpenDialog(this);
        
        // Si el usuario presiona aceptar
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            // Selecciono el fichero
            File fichero = fc.getSelectedFile();
            String datos = "";

            try (FileReader fr = new FileReader(fichero); BufferedReader br = new BufferedReader(fr)) {
                StringBuilder cadena = new StringBuilder();
                String linea;
                int modo = 0;
                String usuarios="";

                while ((linea = br.readLine()) != null) {
                    linea = linea.trim();
                    if (linea.isEmpty()) continue;
                    
                    if (linea.equalsIgnoreCase("usuarios")) {
                        modo = 1;
                        continue;
                    } else if (linea.equalsIgnoreCase("relaciones")) {
                        if (usuarios.endsWith(",")) {
                            usuarios = usuarios.substring(0, usuarios.length() - 1);
                        }
                        String[] user = usuarios.split(",");

                        grafo = new GrafoLA(user.length, true);

                        for (int i = 0; i < user.length; i++) {
                            grafo.insertarVertice(user[i]);
                        }

                        modo = 2;
                        continue;
                    }
                    
                    if (modo == 1) {
                        // Línea de usuarios
                        usuarios += linea+",";
                    }
                    if (modo == 2) {
                        String[] partes = linea.split(",");
                        if (partes.length == 2) {
                            grafo.insertarArista(partes[0].trim(), partes[1].trim());
                        }
                    }
                }
            } catch (IOException e1) {
                e1.printStackTrace();
            }
        } else {
            // Muestra un mensaje de error si no se ha escogido un archivo válido.
            JOptionPane.showMessageDialog(null, "No se escogió un archivo válido");
        }
        
        grafo.mostrar();
    }//GEN-LAST:event_cargarArchivoActionPerformed

    private void enlazarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enlazarActionPerformed
        if (grafo == null){
            JOptionPane.showMessageDialog(null, "Cargue un archivo primero");
            return;
        }
        
        String user1 = this.usuario1.getText().toLowerCase();
        String user2 = this.usuario2.getText().toLowerCase();

        if (user1.length() < 2 || user2.length() < 2) {
            JOptionPane.showMessageDialog(null, "los inputs deben tener al menos 2 letras");
            return;
        }
        
        grafo.insertarArista(user1, user2);
        
        this.usuario1.setText("");
        this.usuario2.setText("");
        
        grafo.mostrar();
    }//GEN-LAST:event_enlazarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        if (grafo == null){
            JOptionPane.showMessageDialog(null, "Cargue un archivo primero");
            return;
        }
        
        String user = this.inputEliminar.getText().toLowerCase();

        if (user.length() < 2) {
            JOptionPane.showMessageDialog(null, "los inputs deben tener al menos 2 letras");
            return;
        }
        
        String respuesta = grafo.eliminarVertice(user);
        this.inputEliminar.setText("");
        JOptionPane.showMessageDialog(null, respuesta);
        //grafo.mostrar();
    }//GEN-LAST:event_eliminarActionPerformed

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        if (grafo == null){
            JOptionPane.showMessageDialog(null, "Cargue un archivo primero");
            return;
        }
        
        String user = this.inputEliminar.getText().toLowerCase();

        if (user.length() < 2) {
            JOptionPane.showMessageDialog(null, "los inputs deben tener al menos 2 letras");
            return;
        }
        
        grafo.insertarVertice(user);
    }//GEN-LAST:event_agregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizar;
    private javax.swing.JButton agregar;
    private javax.swing.JButton cargarArchivo;
    private javax.swing.JButton eliminar;
    private javax.swing.JButton enlazar;
    private javax.swing.JButton identificar;
    private javax.swing.JTextField inputAgregar;
    private javax.swing.JTextField inputEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton mostrarGrafo;
    private javax.swing.JTextField usuario1;
    private javax.swing.JTextField usuario2;
    // End of variables declaration//GEN-END:variables
}
